dist: focal
language: shell

script:
  - echo "âœ… Travis build successful!"

after_success:
  - echo "ðŸš€ Triggering local deploy listener..."
  - curl -X POST https://62de546eaa83.ngrok-free.app/deploy

